### ISSUE TITLE
docx format

### ISSUE THREAD

**Issue by Jamie0** [kiathan/rhulcsnotes#1]
Description of the problem:
The notes use the proprietary and binary docx format.

Steps to reproduce the problem:
1. Clone the repository
2. _Problem officer?_

What should happen:
* Expected some nice LaTeX docs

What actually happened:
* Got some not very nice docx.

**Comment by kiathan** [comment]
U can always convert it and contribute to the repo. Or upload to google
docs to view

**Comment by Jamie0** [comment]
Illegal.

**Comment by kiathan** [comment]
If you are a rhul student, you can download office365 for free as well

**Comment by Jamie0** [comment]
I disagree. Office 365 is proprietary software, and is against the GNU/Linux philosophy of open-ness that this department believes in.

![Attached Image](https://user-images.githubusercontent.com/7827627/32235393-46a13548-be57-11e7-8b73-0af4cf592e49.png)

**Comment by kiathan** [comment]
As I said earlier, the only versions now are only in DOCX format.
It is unlocked and open for all to view.
If you can't open the DOCX, you can seek the department's help in opening one.
If you would like to see a latex version, you are welcomed to make one and contribute to the repo.
